### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-from-Jars#12]
Please make a sample with two independent and runnable jar applications running on same JPro server.
Thanks.

**Comment by FlorianKirmaier** [comment]
Check out this commit: https://github.com/JPro-one/JPro-from-Jars/commit/dab6515f3617647d7365af84e970957905fc8dbc

With this commit, 2 different applications are running on the same server.
Please be aware of the following:
 - Both applications share the same classpath. Libraries should be of the same version
 - Make sure that you don't have a jpro.conf or content in jpro/html in the jars, otherwise, it gets very complicated.
 - Usually "copying jars into this project" won't end in a good workflow. For longterm project-success I would recommend using the gradle or maven project/plugin as a base.
 - It might be cleaner to just host 2 Servers for the different applications.
