### ISSUE TITLE
Alert dialog box was not shown in browser.

### ISSUE THREAD

**Issue by ghost** [JPro-one/JPro-from-Jars#15]
my jar contains three alert dialog box like this

![information-dialog](https://user-images.githubusercontent.com/45443554/86548928-c833f980-bf5b-11ea-935e-4400ab8eea67.png)

When I run with JPro-from-jar it not worked.

How can I show the alert dialog box?

**Comment by FlorianKirmaier** [comment]
`javafx.scene.control.Dialog` is not supported by JPro.
In general blocking API is not supported.
Check out our samples for popups/dialogs:  https://github.com/JPro-one/JPro-Samples
The JFoenix Popups are also a good alternative. 
We've made our checklist in our documentation more explicit about it.

**Comment by Hugolarson** [comment]
There is an issue with JFXDialog. The fonts looks different in JPRO.

![image](https://user-images.githubusercontent.com/8046614/86714591-871a1300-c049-11ea-9c89-e73a9ac3c327.png)

**Comment by ghost** [comment]
@FlorianKirmaier 

How the font is differed? 

How the JPro works?explain.

**Comment by FlorianKirmaier** [comment]
The issue with font isn't related to JFoenix.
I explained it already in the other ticket with the same screenshot.

The look of JavaFX is dependent of the OS because different OS have different fonts.
JPro tries to load the fonts independent of the OS, which is why it sometimes looks different.
But it will always use the same font when the application specifies the used font.
There is also very subtle differences in how fonts are rendered in the browser and how they are rendered in native JavaFX.
But these differences are annoying but not really problematic.

**Comment by Hugolarson** [comment]
Florian,
Same Pane with controls in image looks fine when shown with WebAPI.openStageAsTab (right).
Only when Pane shown in a JFXDialog controls looks blurred like left.
Hope you understand what I mean.

**Comment by FlorianKirmaier** [comment]
@Hugolarson 
Can you provide a small sample on how to create a blurred element with the JFXDialog?
We have a sample-project which already provided a sample-popup based on JFoenix: https://github.com/JPro-one/JPro-Samples, it should be easy to exchange the content. Or show me which content is supposed to be blurred.

**Comment by Hugolarson** [comment]
Making the sample I discovered that it is JFoenix itself that cause the blurring without JPro.
Anyway here is the sample if it's useful to you.


[JproTest.zip](https://github.com/JPro-one/JPro-from-Jars/files/4900992/JproTest.zip)
